### ISSUE TITLE
Your project is not running

### ISSUE THREAD

**Issue by anmol4210** [mlaterman/JellyFish-Attacks-ns-3.19#1]
Hi, I'm new to ns3. and I want to develop projects related to attack in ns3 could you please guide me how to run your project in ns3 because when I copy pastes the file in my ns3 folder, it shows the error : 
 ```
[` 927/2635] Compiling scratch/myTcpBulk.cc
../scratch/myTcpBulk.cc:35:33: fatal error: ns3/jellyfish-queue.h: No such file or directory
compilation terminated.

```

**Comment by mlaterman** [comment]
The files in the `src` directory must be placed with the ns3 source in order for the examples to work.
Also I have not looked at the project in a long time and I don't think i'll be able to help you much more if you encounter further issues, good luck.
